name: JMeter Performance Tests

on:
  push:
    branches: [ main ]

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download Apache JMeter
        run: |
          wget -q https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      - name: Create results folder
        run: mkdir results

      - name: Run JMeter Test
        run: |
          rm -rf reports

          jmeter/bin/jmeter -n \
          -t tests/load_test.jmx \
          -l results/results.jtl \
          -e \
          -o reports \
          -j jmeter.log

      - name: Show generated files
        run: |
          echo "===== REPORTS ====="
          ls -la reports || true

          echo "===== RESULTS ====="
          ls -la results || true

          echo "===== JMETER LOG ====="
          cat jmeter.log || true

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: reports
